"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/providers/AuthProvider";
import { Toaster } from "sonner";
import Header from "@/app/_components/header";
import { Ul } from "./_components/ul";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadat: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideHeaderFooter = pathname === "/login" || pathname === "/sign-up";

  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased ${
            hideHeaderFooter ? "" : "mt-[55px] mb-[40px]"
          }`}
        >
          {!hideHeaderFooter && <Header />}

          {children}

          <Toaster richColors={true} />

          {!hideHeaderFooter && <Ul />}
        </body>
      </AuthProvider>
    </html>
  );
}
